name: daily_counts
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - pytables
  - python=3.10
  - tabulate=0.8.10
  - pandavro=1.7.2
  - pip
  - pip:
    - git+ssh://git@github.com/actigraph/icampam_2024_workshop@3a63308a9c0a199a045112eb57797baee499a763